dist: trusty
sudo: required  # Use the new travis docker based infrastructure

services:
  - docker

git:
  # We need a deeper depth for 'git descibe' to ensure
  # we can reach the last tagged version.
  depth: 99999

language: python
python:
# We don't use the travis python, but we will use it for the build matrix
  - "3.6"

before_install:
  # Create a database for the integration tests.
  - docker pull opendatacube/datacube-core
  - docker build -t opendatacube/datacube-wms .

script:
  # Ensure we are running against the correct python version
  - docker run opendatacube/datacube-wms /bin/sh -c "./check-code.sh"

